from dataclasses import dataclass, field
from enum import StrEnum
from typing import List

class TargetAction(StrEnum):
  DNS_SERVERS_ADD         = 'DNS_SERVERS_ADD'
  DNS_SERVERS_DELETE_ALL  = 'DNS_SERVERS_DELETE_ALL'
  DNS_SERVERS_DELETE      = 'DNS_SERVERS_DELETE'
  #
  DOMAINS_LISTS_ADD         = 'DOMAINS_LISTS_ADD'
  DOMAINS_LISTS_DELETE_ALL  = 'DOMAINS_LISTS_DELETE_ALL'
  DOMAINS_LISTS_DELETE      = 'DOMAINS_LISTS_DELETE'
  DOMAINS_LISTS_UPDATE      = 'DOMAINS_LISTS_UPDATE'
  #
  DOMAINS_ADD         = 'DOMAINS_ADD'
  DOMAINS_RESOLVED    = 'DOMAINS_RESOLVED'
  DOMAINS_DELETE_ALL  = 'DOMAINS_DELETE_ALL'
  DOMAINS_DELETE      = 'DOMAINS_DELETE'
  #
  IPS_LISTS_ADD         = 'IPS_LISTS_ADD'
  IPS_LISTS_DELETE_ALL  = 'IPS_LISTS_DELETE_ALL'
  IPS_LISTS_DELETE      = 'IPS_LISTS_DELETE'
  IPS_LISTS_UPDATE      = 'IPS_LISTS_UPDATE'
  #
  IPS_ADD           = 'IPS_ADD'
  IPS_ADD_RESOLVED  = 'IPS_ADD_RESOLVED'
  IPS_DELETE_ALL    = 'IPS_DELETE_ALL'
  IPS_DELETE_ID     = 'IPS_DELETE_ID'
  IPS_DELETE_ADDR   = 'IPS_DELETE_ADDR'
  #
  ROS_CONFIG_ADD         = 'ROS_CONFIG_ADD'
  ROS_CONFIG_DELETE_ALL  = 'ROS_CONFIG_DELETE_ALL'
  ROS_CONFIG_DELETE      = 'ROS_CONFIG_DELETE'

@dataclass
class QueueElementDto:
  target: TargetAction
  elements: List = field(default_factory=list)
